"""Add cart and cart_items tables

Revision ID: fe83a99d7ed6
Revises: 153ea36157a8
Create Date: 2026-02-19 22:03:40.016974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe83a99d7ed6'
down_revision: Union[str, Sequence[str], None] = '153ea36157a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
